/* WALLPR catalog.
   To add a wallpaper: drop a preview image in assets/previews/ and add an entry
   to WALLPAPERS. Previews should be downscaled/compressed (~1400px wide max) —
   full-resolution files are uploaded ONLY to the checkout provider, never here.
   buyUrl: paste the hosted-checkout link (Lemon Squeezy / Stripe Managed
   Payments / Payhip). Leave "" to show a disabled "Coming soon" button. */

const CATEGORIES = {
  sports: {
    title: "Sports",
    kicker: "Collection 01",
    tagline: "Fight nights and finish lines, rendered in thick oil strokes.",
    cover: "assets/covers/sports.webp?v=7",
    bundle: { label: "The Sports pack", price: 10, buyUrl: "" },
  },
  places: {
    title: "Places",
    kicker: "Collection 02",
    tagline: "Cities and coastlines the way a palette knife remembers them.",
    cover: "assets/covers/places.webp?v=7",
    bundle: { label: "The Places pack", price: 10, buyUrl: "" },
  },
  lifestyle: {
    title: "Lifestyle",
    kicker: "Collection 03",
    tagline: "Machines, style and slow evenings in impasto.",
    cover: "assets/covers/lifestyle.webp?v=7",
    bundle: { label: "The Lifestyle pack", price: 10, buyUrl: "" },
  },
  animals: {
    title: "Animals",
    kicker: "Collection 04",
    tagline: "Creatures painted in motion, texture you can almost touch.",
    cover: "assets/covers/animals.webp?v=7",
    bundle: { label: "The Animals pack", price: 10, buyUrl: "" },
  },
};

const WALLPAPERS = [
  {
    id: "places-01",
    title: "Santorini Gold",
    category: "places",
    preview: "assets/previews/places-01.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-02",
    title: "Second City Nights",
    category: "places",
    preview: "assets/previews/places-02.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-03",
    title: "Desert Vigil",
    category: "places",
    preview: "assets/previews/places-03.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-04",
    title: "Golden Range",
    category: "places",
    preview: "assets/previews/places-04.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-01",
    title: "Golden Gate Run",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-01.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-02",
    title: "Click Wheel",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-02.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-03",
    title: "Night Pods",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-03.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-04",
    title: "Mach Sunset",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-04.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-05",
    title: "Snowstorm Bull",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-05.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-06",
    title: "Ibiza Run",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-06.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-07",
    title: "Floating World",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-07.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "animals-01",
    title: "Night Serpent",
    category: "animals",
    preview: "assets/previews/animals-01.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "sports-02",
    title: "Twelve Rounds",
    category: "sports",
    preview: "assets/previews/sports-02.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-05",
    title: "Cinque Sera",
    category: "places",
    preview: "assets/previews/places-05.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-06",
    title: "Iron Lady",
    category: "places",
    preview: "assets/previews/places-06.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-07",
    title: "Empire Dusk",
    category: "places",
    preview: "assets/previews/places-07.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-08",
    title: "Last Sip of Summer",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-08.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-09",
    title: "Boiler Room",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-09.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-10",
    title: "Downbeat",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-10.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-11",
    title: "Bianco",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-11.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-12",
    title: "Shutter Heart",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-12.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "animals-02",
    title: "Golden Hour King",
    category: "animals",
    preview: "assets/previews/animals-02.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "sports-03",
    title: "Powder Day",
    category: "sports",
    preview: "assets/previews/sports-03.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-08",
    title: "Costiera",
    category: "places",
    preview: "assets/previews/places-08.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-09",
    title: "Lido",
    category: "places",
    preview: "assets/previews/places-09.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-13",
    title: "Golden Hour Villa",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-13.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-14",
    title: "Terrazza",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-14.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "sports-04",
    title: "The Contender",
    category: "sports",
    preview: "assets/previews/sports-04.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "sports-05",
    title: "Nothing But Net",
    category: "sports",
    preview: "assets/previews/sports-05.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-15",
    title: "Stacked",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-15.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-16",
    title: "Midnight Diver",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-16.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-17",
    title: "Matte Black",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-17.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "lifestyle-18",
    title: "Quiet Sail",
    category: "lifestyle",
    preview: "assets/previews/lifestyle-18.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-10",
    title: "Last Light",
    category: "places",
    preview: "assets/previews/places-10.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-11",
    title: "Moonline",
    category: "places",
    preview: "assets/previews/places-11.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-12",
    title: "Fog City",
    category: "places",
    preview: "assets/previews/places-12.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-13",
    title: "Neon Canyon",
    category: "places",
    preview: "assets/previews/places-13.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-14",
    title: "Lantern Rain",
    category: "places",
    preview: "assets/previews/places-14.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-15",
    title: "Westminster Blue",
    category: "places",
    preview: "assets/previews/places-15.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-16",
    title: "Brooklyn Nights",
    category: "places",
    preview: "assets/previews/places-16.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-17",
    title: "Canal Dusk",
    category: "places",
    preview: "assets/previews/places-17.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-18",
    title: "Last Stop Diner",
    category: "places",
    preview: "assets/previews/places-18.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "places-19",
    title: "Eternal City",
    category: "places",
    preview: "assets/previews/places-19.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "animals-03",
    title: "Amber Eyes",
    category: "animals",
    preview: "assets/previews/animals-03.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "animals-04",
    title: "Night Prowl",
    category: "animals",
    preview: "assets/previews/animals-04.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "animals-05",
    title: "Breach",
    category: "animals",
    preview: "assets/previews/animals-05.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
  {
    id: "animals-06",
    title: "Whiteout",
    category: "animals",
    preview: "assets/previews/animals-06.jpg",
    sizes: ["Desktop"],
    price: 3.99,
    buyUrl: "",
  },
];
